#' @title Get Body Fat Logs
#'
#' @description
#'   \code{get_body_fat_logs()} retrieves a list of all user's body fat log entries for a given day.
#'
#' @param date The end date of the period specified in the format yyyy-MM-dd or today.
#' @param base_date	The range start date, in the format yyyy-MM-dd or today.
#' @param period The range for which data will be returned. Options are 1d, 7d, 30d, 1w, or 1m.
#' @param end_date The end date of the range. The period must not be longer than 31 days.
#'
#' @export
get_body_fat_logs <- function(token, date = "", base_date = "", period = "", end_date = "", simplify = TRUE) {
  url <- if (date != "" && period != "") {
    paste0(url_body, sprintf("log/fat/date/%s/%s.json", format_date(date), period))
  } else if (base_date != "" & end_date != "") {
    paste0(url_body, sprintf("log/fat/date/%s/%s.json", format_date(base_date), format_date(end_date)))
  } else if (date != "") {
    paste0(url_body, sprintf("log/fat/date/%s.json", format_date(date)))
  }
  tidy_output(get(url, token), simplify)
}

#' @title Get Body Time Series
#'
#' @description
#' \code{get_body()} returns time series data in the specified range for a given resource.
#'
#' @param resource_path	The resource path. Options are "bmi", "fat", or "weight".
#' @param base_date The range start date, in the format yyyy-MM-dd or today.
#' @param end_date The end date of the range.
#' @param date The end date of the period specified in the format yyyy-MM-dd or today.
#' @param period The range for which data will be returned. Options are 1d, 7d, 30d, 1w, 1m, 3m, 6m, 1y, or max.
#'
#' @export
get_body <- function(token, resource_path, base_date = NULL, end_date = NULL, date = NULL, period = NULL) {
  url <- if (!is.null(date) && !is.null(period)) {
    paste0(url_body, sprintf("%s/date/%s/%s.json", resource_path, format_date(date), period))
  } else if (!is.null(base_date) && !is.null(end_date)) {
    paste0(url_body, sprintf("%s/date/%s/%s.json", resource_path, format_date(base_date), format_date(end_date)))
  } else {
    stop("Please supply either base_date and end_date or date and period parameters.")
  }
  get(url, token)[[1]]
}

#' @title Get Body Goals
#'
#' @description
#'   \code{get_body_goals()} retrieves a user's current body fat percentage or weight goal.
#'
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @param goal_type weight or fat
#'
#' @export
get_body_goals <- function(token, goal_type) {
  if (!(goal_type %in% c("weight", "fat"))) {
    stop("goal_type must be one of 'weight' or 'fat'")
  }
  url <- paste0(url_body, sprintf("log/%s/goal.json", goal_type))
  get(url, token)
}

#' @title Get Weight Logs
#'
#' @description
#'   \code{get_weight_logs()} returns time series data in the specified range for a given resource.
#'
#' @param date The end date of the period specified in the format yyyy-MM-dd or today.
#' @param base_date The range start date, in the format yyyy-MM-dd or today.
#' @param period The range for which data will be returned. Options are 1d, 7d, 30d, 1w, or 1m.
#' @param end_date The end date of the range. The period must not be longer than 31 days.
#'
#' @export
get_weight_logs <- function(token, date = NULL, base_date = NULL, period = NULL, end_date = NULL) {
  url <- if (!is.null(date) && !is.null(period)) {
    paste0(url_body, sprintf("log/weight/date/%s/%s.json", format_date(date), period))
  } else if (!is.null(base_date) && !is.null(end_date)) {
    paste0(url_body, sprintf("log/weight/date/%s/%s.json", format_date(base_date), format_date(end_date)))
  } else if (!is.null(date)) {
    paste0(url_body, sprintf("log/weight/date/%s.json", format_date(date)))
  }
  get(url, token)[[1]]
}
